### PR TITLE
connect module development

### PR DESCRIPTION
**Pull request by spektra2147**

### CODE REVIEW

**Review by fatihalp — APPROVED** [review]

**Comment by diashalabi** [comment]
You can use this function

    public function getModelRepo($model)
    {
        $modelNamespace = explode('\\', $model);
        $modelName = array_pop($modelNamespace);
        preg_match('/^(.*)Model$/', $modelName, $m);
        $modelName = $m[1];
        $repoNamespace = implode('\\', $modelNamespace);

        return app("$repoNamespace\Contract\\{$modelName}RepositoryInterface");
    }

To use it simply do this

`$this->getModelRepo(AdvModel::class)->find(1)`

**Comment by spektra2147** [comment]
@diashalabi 

"Anomaly\Streams\Platform\Model\Advs\AdvsAdvsEntryModel"

please use this class

**Comment by spektra2147** [comment]
Ekran Resmi 2021-08-18 14 27 57

**Comment by diashalabi** [comment]
> @diashalabi
> 
> "Anomaly\Streams\Platform\Model\Advs\AdvsAdvsEntryModel"
> 
> please use this class

You can do this

    public function getModelRepo($entryModel)
    {
        $model = get_class(app($entryModel));
        $modelNamespace = explode('\\', $model);
        $modelName = array_pop($modelNamespace);
        preg_match('/^(.*)Model$/', $modelName, $m);
        $modelName = $m[1];
        $repoNamespace = implode('\\', $modelNamespace);

        return app("$repoNamespace\Contract\\{$modelName}RepositoryInterface");
    }

To use it simply do this

        $this->getModelRepo('Anomaly\Streams\Platform\Model\Advs\AdvsAdvsEntryModel')->find(1);

**Pull request closed without merging**
